/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package consultorio.interfazGrafica;

import consultorio.clasesApp.*;
import consultorio.excepciones.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author facun
 */
public class VentanaAgenda extends javax.swing.JInternalFrame {
    
    Consultorio consultorio = Consultorio.singleton();
    
    List<Odontologo> odontologos = consultorio.getArrayOdontologos();
    
    List<Paciente> pacientes = consultorio.getArrayPacientes();
    /**
     * Creates new form VentanaAgenda
     */
    public VentanaAgenda() {
        initComponents();
        
        for(Odontologo i: odontologos){
            comboBoxOdontologos.addItem(i);
        }
        
        for(Paciente i: pacientes){
            comboBoxPacientes.addItem(i);
        }
        
        DefaultTableModel datos = (DefaultTableModel) tablaTurnos.getModel();
        
        datos.setNumRows(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxOdontologos = new javax.swing.JComboBox();
        botonMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTurnos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        campoDocumento = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        comboBoxPacientes = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        campoDia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoMes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoAño = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoHora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoMinuto = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        campoMotivo = new javax.swing.JTextField();
        rbDobleTurno = new javax.swing.JRadioButton();
        botonEliminar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campoDiaNoAtencion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoMesNoAtencion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        campoAñoNoAtencion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        campoHoraNoAtencion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        campoMinutoNoAtencion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        campoHoraFinNoAtencion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        campoMinutoFinNoAtencion = new javax.swing.JTextField();
        botonAgregarNoAtencion = new javax.swing.JButton();
        botonVerNoAtencion = new javax.swing.JButton();

        setClosable(true);
        setTitle("Agendas");

        jLabel1.setText("Agenda:");

        botonMostrar.setText("Mostrar/Actualizar");
        botonMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMostrarMouseClicked(evt);
            }
        });

        tablaTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Paciente", "Fecha", "Hora Inicio", "Hora Fin", "Motivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaTurnos);

        jLabel2.setText("Buscar turno (Documento)");

        botonBuscar.setText("Buscar");
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarMouseClicked(evt);
            }
        });

        jLabel4.setText("Paciente:");

        comboBoxPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPacientesActionPerformed(evt);
            }
        });

        jLabel5.setText("Dia:");

        campoDia.setText("dd");

        jLabel6.setText("Mes:");

        campoMes.setText("mm");

        jLabel7.setText("Año:");

        campoAño.setText("aaaa");

        jLabel8.setText("Hora:");

        campoHora.setText("hh");

        jLabel9.setText("Minuto:");

        campoMinuto.setText("mm");

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        jLabel10.setText("Motivo:");

        rbDobleTurno.setText("Asignar doble turno?");

        botonEliminar.setText("Eliminar");
        botonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEliminarMouseClicked(evt);
            }
        });

        botonModificar.setText("Modificar");
        botonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonModificarMouseClicked(evt);
            }
        });

        jLabel3.setText("Fecha y Hora en el que no se atendera en el horario de consultas predefinido:");

        jLabel11.setText("Dia:");

        campoDiaNoAtencion.setText("dd");

        jLabel12.setText("Mes:");

        campoMesNoAtencion.setText("mm");

        jLabel13.setText("Año:");

        campoAñoNoAtencion.setText("aaaa");

        jLabel14.setText("Hora Inicio:");

        campoHoraNoAtencion.setText("hh");

        jLabel15.setText("Minuto Inicio:");

        campoMinutoNoAtencion.setText("mm");

        jLabel16.setText("Hora Fin:");

        campoHoraFinNoAtencion.setText("hh");

        jLabel17.setText("Minuto Fin:");

        campoMinutoFinNoAtencion.setText("mm");

        botonAgregarNoAtencion.setText("Agregar");
        botonAgregarNoAtencion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAgregarNoAtencionMouseClicked(evt);
            }
        });

        botonVerNoAtencion.setText("Ver");
        botonVerNoAtencion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVerNoAtencionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMotivo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoAño, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxPacientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbDobleTurno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxOdontologos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonMostrar))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(2, 2, 2)
                        .addComponent(campoDiaNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMesNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoAñoNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoHoraNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMinutoNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoHoraFinNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoMinutoFinNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVerNoAtencion)
                        .addGap(18, 18, 18)
                        .addComponent(botonAgregarNoAtencion)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxOdontologos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(campoDiaNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(campoMesNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(campoAñoNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(campoHoraNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(campoMinutoNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(campoHoraFinNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(campoMinutoFinNoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregarNoAtencion)
                    .addComponent(botonVerNoAtencion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar)
                    .addComponent(botonEliminar)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(campoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(campoAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(campoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(campoMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rbDobleTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar)
                    .addComponent(botonModificar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseClicked
        try{
            Object o = comboBoxOdontologos.getSelectedItem();
        
            if(o instanceof Odontologo){
                Odontologo odontologo = (Odontologo) o;
            
                IntAgenda agenda = odontologo.getAgendaPersonal();
            
                List<Turno> turnoEncontrado = new ArrayList<>();
            
                turnoEncontrado.add(agenda.buscarTurno(Integer.parseInt(campoDocumento.getText())));
            
                DefaultTableModel datos = (DefaultTableModel) tablaTurnos.getModel();
        
                datos.setNumRows(0);
        
                for(Turno i: turnoEncontrado){
            
                    Object[] fila = { i.getPaciente().toString(), i.getFecha(), i.getHoraInicio(), i.getHoraFin(), i.getMotivo()};
                    datos.addRow(fila);
                }
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Se cargaron mal los datos.");
        }catch(TurnoNoExisteException e){
            JOptionPane.showMessageDialog(null, "El turno no existe.");
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error.");
        }
        
       
    }//GEN-LAST:event_botonBuscarMouseClicked

    private void botonMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMostrarMouseClicked
        Object o = comboBoxOdontologos.getSelectedItem();
        
        if(o instanceof Odontologo){
            Odontologo odontologo = (Odontologo) o;
            
            IntAgenda agenda = odontologo.getAgendaPersonal();
            
            List<Turno> turnos = agenda.mostrarTurnos();
            
            DefaultTableModel datos = (DefaultTableModel) tablaTurnos.getModel();
        
            datos.setNumRows(0);
        
            for(Turno i: turnos){
            
                Object[] fila = { i.getPaciente().toString(), i.getFecha(), i.getHoraInicio(), i.getHoraFin(), i.getMotivo()};
                datos.addRow(fila);
            }
        }
        
    }//GEN-LAST:event_botonMostrarMouseClicked

    private void comboBoxPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPacientesActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        try{
            Object o1 = comboBoxOdontologos.getSelectedItem();
        
            Object o2 = comboBoxPacientes.getSelectedItem();
       
            Odontologo odontologoElegido = (Odontologo) o1;
            Paciente pacienteElegido = (Paciente) o2;
            
            IntAgenda agenda = odontologoElegido.getAgendaPersonal();
               
            Integer dia = Integer.parseInt(campoDia.getText());
            Integer mes = Integer.parseInt(campoMes.getText());
            Integer año = Integer.parseInt(campoAño.getText());
            Integer hora = Integer.parseInt(campoHora.getText());
            Integer minutos = Integer.parseInt(campoMinuto.getText());
            String motivo = campoMotivo.getText();
                
            Turno turno = new Turno(pacienteElegido, LocalDate.of(año, mes, dia), LocalTime.of(hora, minutos), motivo);
                
            agenda.agregarTurno(turno, rbDobleTurno.isSelected());
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Se cargaron mal los datos.");
        }catch(TurnoNoCargadoException e){
            JOptionPane.showMessageDialog(null, "Verifique la fecha y los horarios.");
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error.");
        }
        
        campoDia.setText("");
        campoMes.setText("");
        campoAño.setText("");
        campoHora.setText("");
        campoMinuto.setText("");
        campoMotivo.setText("");
        rbDobleTurno.setSelected(false);
        
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseClicked
        try{
            Object o = comboBoxOdontologos.getSelectedItem();
        
            if(o instanceof Odontologo){
                Odontologo odontologo = (Odontologo) o;
            
                IntAgenda agenda = odontologo.getAgendaPersonal();
                
                agenda.eliminarTurno(Integer.parseInt(campoDocumento.getText()));
            
                JOptionPane.showMessageDialog(null, "El Turno fue eliminado de la lista correctamente");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Se cargaron mal los datos.");
        }catch(TurnoNoExisteException e){
            JOptionPane.showMessageDialog(null, "El turno no existe.");
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error.");
        }
        
        campoDocumento.setText("");
    }//GEN-LAST:event_botonEliminarMouseClicked

    private void botonModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonModificarMouseClicked
        try{
            Object o1 = comboBoxOdontologos.getSelectedItem();
       
            Odontologo odontologoElegido = (Odontologo) o1;
            
            IntAgenda agenda = odontologoElegido.getAgendaPersonal();
               
            Integer documento = Integer.parseInt(campoDocumento.getText());
            Integer dia = Integer.parseInt(campoDia.getText());
            Integer mes = Integer.parseInt(campoMes.getText());
            Integer año = Integer.parseInt(campoAño.getText());
            Integer hora = Integer.parseInt(campoHora.getText());
            Integer minutos = Integer.parseInt(campoMinuto.getText());
            String motivo = campoMotivo.getText();
            Boolean dobleTurno = rbDobleTurno.isSelected();
                
            agenda.modificarTurno(documento, LocalDate.of(año, mes, dia), LocalTime.of(hora, minutos), motivo, dobleTurno);
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Se cargaron mal los datos.");
        }catch(TurnoNoExisteException e){
            JOptionPane.showMessageDialog(null, "El turno buscado no existe.");
        }catch(TurnoNoCargadoException e){
            JOptionPane.showMessageDialog(null, "Verifique la fecha y los horarios.");
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error.");
        }
        
        campoDia.setText("");
        campoMes.setText("");
        campoAño.setText("");
        campoHora.setText("");
        campoMinuto.setText("");
        campoMotivo.setText("");
        rbDobleTurno.setSelected(false);
        
    }//GEN-LAST:event_botonModificarMouseClicked

    private void botonAgregarNoAtencionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarNoAtencionMouseClicked
        try{
            Object o1 = comboBoxOdontologos.getSelectedItem();
       
            Odontologo odontologoElegido = (Odontologo) o1;
            
            IntAgenda agenda = odontologoElegido.getAgendaPersonal();
               
            Integer dia = Integer.parseInt(campoDiaNoAtencion.getText());
            Integer mes = Integer.parseInt(campoMesNoAtencion.getText());
            Integer año = Integer.parseInt(campoAñoNoAtencion.getText());
            Integer hora = Integer.parseInt(campoHoraNoAtencion.getText());
            Integer minutos = Integer.parseInt(campoMinutoNoAtencion.getText());
            Integer horaFin = Integer.parseInt(campoHoraFinNoAtencion.getText());
            Integer minutosFin = Integer.parseInt(campoMinutoFinNoAtencion.getText());
                
            TurnoSinAtencion turnoSinAtencion = new TurnoSinAtencion(LocalDate.of(año, mes, dia), LocalTime.of(hora, minutos), LocalTime.of(horaFin, minutosFin) );
                
            agenda.agregarTurnoSinAtencion(turnoSinAtencion);
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Se cargaron mal los datos.");
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error.");
        }
        
        campoDiaNoAtencion.setText("");
        campoMesNoAtencion.setText("");
        campoAñoNoAtencion.setText("");
        campoHoraNoAtencion.setText("");
        campoMinutoNoAtencion.setText("");
        campoHoraFinNoAtencion.setText("");
        campoMinutoFinNoAtencion.setText("");
    }//GEN-LAST:event_botonAgregarNoAtencionMouseClicked

    private void botonVerNoAtencionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerNoAtencionMouseClicked
        VentanaListaTurnosBloqueados v = new VentanaListaTurnosBloqueados();
        InterfazPrincipal.panelEscritorio.add(v);
        v.show();
    }//GEN-LAST:event_botonVerNoAtencionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAgregarNoAtencion;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonVerNoAtencion;
    private javax.swing.JTextField campoAño;
    private javax.swing.JTextField campoAñoNoAtencion;
    private javax.swing.JTextField campoDia;
    private javax.swing.JTextField campoDiaNoAtencion;
    private javax.swing.JTextField campoDocumento;
    private javax.swing.JTextField campoHora;
    private javax.swing.JTextField campoHoraFinNoAtencion;
    private javax.swing.JTextField campoHoraNoAtencion;
    private javax.swing.JTextField campoMes;
    private javax.swing.JTextField campoMesNoAtencion;
    private javax.swing.JTextField campoMinuto;
    private javax.swing.JTextField campoMinutoFinNoAtencion;
    private javax.swing.JTextField campoMinutoNoAtencion;
    private javax.swing.JTextField campoMotivo;
    private javax.swing.JComboBox comboBoxOdontologos;
    private javax.swing.JComboBox comboBoxPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rbDobleTurno;
    private javax.swing.JTable tablaTurnos;
    // End of variables declaration//GEN-END:variables
}
